### ISSUE TITLE
Very simple lotto-like game

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/p2p-games#1]
Implement the following console game:
1. Each player generates 5 numbers from 1 to 30 and enters them in a program.
2. Program checks that the input is correct (all numbers are different) and sends some evidence of this set to chat (e.g. md5 of the sorted sequence written as text).
3. Then program sends the actual sequence to chat (so that other players can now check that this is the actual input).
4. Then the game starts: players generate a random number from 1 to 30 and cross out the number in sequence if it is there. Each next number should be different from others.
5. The game lasts until one of the sequences is crossed out completely. The corresponding player is the winner.

Variation:
The program can also check that there are no same sequences. If there are, the step 1-3 should be repeated.

**Comment by wimag** [comment]
closed by 94c662cf6fff800dd1013e18d69e8f30d64f0aa2
